POST http://localhost:8080/monitors
Content-Type: application/json

{
  "id": "device-23",
  "timeout": 6,
  "alert_email": "admin@critmon.com"
}

###

POST http://localhost:8080/monitors/device-23/heartbeat

###
POST http://localhost:8080/monitors/device-23/heartbeat

### epiration
GET http://localhost:8080/monitors/device-23